// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGT.Entities
{
    public partial class Cv
    {
        public Cv()
        {
            Education = new HashSet<Education>();
            Experience = new HashSet<Experience>();
            Interest = new HashSet<Interest>();
            Language = new HashSet<Language>();
            Skills = new HashSet<Skills>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public int? Age { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Linkedin { get; set; }
        public string Photo { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Education> Education { get; set; }
        public virtual ICollection<Experience> Experience { get; set; }
        public virtual ICollection<Interest> Interest { get; set; }
        public virtual ICollection<Language> Language { get; set; }
        public virtual ICollection<Skills> Skills { get; set; }
    }
}