// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGT.Entities
{
    public partial class Education
    {
        public int Id { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public string Label { get; set; }
        public string Institute { get; set; }
        public int? CvId { get; set; }

        public virtual Cv Cv { get; set; }
    }
}