// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGT.Entities
{
    public partial class Experience
    {
        public Experience()
        {
            SkillsExperience = new HashSet<SkillsExperience>();
            Tasks = new HashSet<Tasks>();
        }

        public int Id { get; set; }
        public int CvId { get; set; }
        public DateTime DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }

        public virtual Cv Cv { get; set; }
        public virtual ICollection<SkillsExperience> SkillsExperience { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}