// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGT.Entities
{
    public partial class Skills
    {
        public Skills()
        {
            SkillsExperience = new HashSet<SkillsExperience>();
        }

        public int Id { get; set; }
        public int CvId { get; set; }
        public string Label { get; set; }

        public virtual Cv Cv { get; set; }
        public virtual ICollection<SkillsExperience> SkillsExperience { get; set; }
    }
}