// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGT.Entities
{
    public partial class Tasks
    {
        public int Id { get; set; }
        public int ExperienceId { get; set; }
        public string Label { get; set; }

        public virtual Experience Experience { get; set; }
    }
}